services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./dev.db:/app/dev.db
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=production
    command: sh -c "npx prisma migrate deploy && node server.js"
